### ISSUE TITLE
Backport bugs and RFE for 5.7.2-capstan

### ISSUE THREAD

**Issue by briacp** [briacp/omegat#3]
- [x] #1
  - [RFE#1695](https://sourceforge.net/p/omegat/feature-requests/1695/) - Select output format for statistics output: JSON, XML or Text (omegat-org/omegat#675)
  - [RFE#1690](https://sourceforge.net/p/omegat/feature-requests/1690/) - Have "Commit Target Files" also commit statistics file (omegat-org/omegat#676)
  - [BUGS#1164](https://sourceforge.net/p/omegat/bugs/1164/) - Fix reloading TMX after team synchronization (omegat-org/omegat#645)
- [x] #2
  - [BUG#1176](https://sourceforge.net/p/omegat/bugs/1176/) - The COMPILE event is fired *after* the target commit (omegat-org/omegat#609)
- [x] #7 
  - [RFE#1670](https://sourceforge.net/p/omegat/feature-requests/1670/) - Share authentication between Git or SVN repositories on the same server (omegat-org/omegat@6c7b8ff415b7d6a730cca99b6341f3c885f6beb6, omegat-org/omegat@1a15c45606883bc7394015a234ea5b6ac0117d38)
- [x] #4
  - [BUG#1140](https://sourceforge.net/p/omegat/bugs/1140/) - Context-bound matches are ignored in /tm/auto (omegat-org/omegat#443)
  - [BUG#1092](https://sourceforge.net/p/omegat/bugs/1092/) - Enforced ID-bound alternative translations not recognized (omegat-org/omegat@2f531b92992b662207cd27589c661d1f93cc92d7)
- [x] #6
  - [BUG#1101](https://sourceforge.net/p/omegat/bugs/1101/) - No ID-bound matching in /tm/tmx2source (omegat-org/omegat@3855272e667ae85b0ffd35d0fca99ef0ffaaa528)
- [x] #5 
  - [BUG#1003](https://sourceforge.net/p/omegat/bugs/1003/) - Matches containing non-alphabetical text are ignored in TM leverage (omegat-org/omegat#467, omegat-org/omegat@2228c117835118a5ea9bf690e8cec9df3a4eef36)
- [x] #9
  - [RFE#1672](https://sourceforge.net/p/omegat/feature-requests/1672/) - Hide tag-only segments (omegat-org/omegat#503)
- [ ] TODO
  - [RFE#1519](https://sourceforge.net/p/omegat/feature-requests/1519/) - OmegaT uses wrong/old version of plugin in case of conflict (omegat-org/omegat#646)
- [ ] [RFE#1608](https://sourceforge.net/p/omegat/feature-requests/1608/) - Add notes to the translator in /tm/notes/foo.tmx
- [ ] [BUG#1185](https://sourceforge.net/p/omegat/bugs/1185/) - Saving does not register pre-translation in new projects
- [x] ~~[BUG#1002](https://sourceforge.net/p/omegat/bugs/1002/) - Choice of GUI language during re-installation is ignored~~ (already in 5.7.1 from omegat-org/omegat@c5129fd30fa04b7c05db1bde9a10c5f805ffe91d)
- [x] ~~[BUG#988](https://sourceforge.net/p/omegat/bugs/988/) - RLE and LRE control characters not visible in editor~~ (already in 5.7.1)
